const Nav=()=> <nav><a href="#home" className="brand">SM</a><div><a href="#about">About</a><a href="#involvement">Interests</a><a href="#review">Year in Review</a><a href="#honors">Honors</a><a href="#contact">Contact</a></div></nav>;

const years=[
  {year:"2026–27",label:"First Year",active:true,text:"My first Year-in-Review will be added after the Spring 2027 semester. I’ll use it to reflect on the experiences that shaped my first year, the progress I made toward my goals, and what I want to pursue next."},
  {year:"2027–28",label:"Second Year",text:"Future annual reflection."},
  {year:"2028–29",label:"Third Year",text:"Future annual reflection."},
  {year:"2029–30",label:"Fourth Year",text:"Future annual reflection."}
];

export default function Page(){return <main><Nav/>
<section id="home" className="hero"><div className="eyebrow">UNIVERSITY OF CINCINNATI • UNIVERSITY HONORS PROGRAM</div><h1>Sean<br/><span>McCulloch.</span></h1><p className="lead">Information Technology — Software Application Development. Developer, builder, and first-year Honors student at UC.</p><div className="heroActions"><a className="button" href="#about">Explore my portfolio ↓</a><a className="ghostButton" href="https://github.com/SeanSpon" target="_blank" rel="noreferrer">GitHub ↗</a></div></section>

<section id="about"><div className="sectionTag">01 / ABOUT ME</div><div className="grid"><div><div className="photo"><span>PHOTO COMING SOON</span><small>Professional photo placeholder</small></div></div><div><h2>Building things that<br/>actually <em>work.</em></h2><p>I’m Sean McCulloch, an Information Technology student at the University of Cincinnati studying Software Application Development and a member of the University Honors Program. I’m originally from Louisville, Kentucky, where I attended Trinity High School.</p><p>I’ve always been drawn to computers, problem solving, and figuring out how technology works. That interest grew into building websites and software projects of my own. I co-founded SeeZee Studio, where I work on real technology projects and continue learning about development, systems, business, communication, and turning ideas into useful products.</p><p>At UC, I want to keep expanding beyond what I already know. I’m interested in software development, artificial intelligence, cybersecurity, entrepreneurship, and the ways technology can solve real problems. Through the Honors Program, I hope to challenge myself outside the classroom, meet people with different interests and perspectives, and become a stronger student and leader.</p><p>Outside of technology, I enjoy lifting, hockey, spending time with friends, and setting new goals for myself. By graduation, I want strong technical experience, meaningful co-op and internship work, a network of people I’ve learned from, and a portfolio that shows how much I’ve grown.</p></div></div></section>

<section id="involvement" className="alt"><div className="sectionTag">02 / INVOLVEMENT & INTERESTS</div><h2>What I’m into.</h2><p className="sectionIntro">These are the areas I’m involved in now and the directions I want to explore during my time at UC.</p><div className="cards"><article><b>01</b><h3>Technology & Software</h3><p>Software development, web development, AI, cybersecurity, and learning new tools by building with them.</p></article><article><b>02</b><h3>SeeZee Studio</h3><p>Co-founder of a technology studio where I get experience building real digital products and solving practical problems.</p><a className="textLink" href="https://seezeestudios.com" target="_blank" rel="noreferrer">Visit SeeZee ↗</a></article><article><b>03</b><h3>Fitness & Hockey</h3><p>Lifting and hockey have taught me consistency, competition, teamwork, and the value of measurable goals.</p></article><article><b>04</b><h3>UC Involvement</h3><p>I’m exploring Honors opportunities, student organizations, professional experiences, co-ops, and new communities on campus.</p></article></div></section>

<section id="review"><div className="sectionTag">03 / YEAR IN REVIEW</div><h2 className="sectionTitle">Growth, year by year.</h2><p className="sectionIntro darkText">Each academic year, this section will become a record of the bigger picture: what I learned, what changed, and where I want to go next.</p><div className="timeline">{years.map((item,i)=><article className={item.active?"yearCard active":"yearCard future"} key={item.year}><div><span>{item.label}</span><h3>{item.year}</h3></div><p>{item.text}</p>{item.active&&<small>Reflection to be completed by June 5, 2027.</small>}</article>)}</div></section>

<section id="honors" className="alt"><div className="sectionTag">04 / HONORS EXPERIENCES</div><h2 className="sectionTitle">Experience showcases.</h2><p className="sectionIntro">I’m at the beginning of my Honors journey, so there are no completed showcases yet. As I finish Honors experiences, each one will get its own page or showcase with a concise reflection and an artifact representing what I learned.</p><div className="emptyShowcase"><div className="emptyNumber">01</div><div><span>UPCOMING</span><h3>First Honors Experience</h3><p>No completed experience yet. This space is intentionally ready for my first showcase.</p></div></div></section>

<section id="contact"><div className="sectionTag">05 / CONTACT & LINKS</div><div className="contactGrid"><div><h2>Keep<br/><em>building.</em></h2></div><div><p>This portfolio will continue to grow throughout my time at the University of Cincinnati.</p><a href="https://github.com/SeanSpon" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://seezeestudios.com" target="_blank" rel="noreferrer">SeeZee Studio ↗</a></div></div></section>
<footer><b>Sean McCulloch</b><span>University of Cincinnati • Information Technology • University Honors Program</span><span>© 2026</span></footer></main>}
